cask_args appdir: "/Applications"

tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/services"

brew "doxygen"
brew "htop"
brew "imagemagick"
brew "nginx"
brew "nvm"
brew "python3"
brew "sqlite"
brew "ssh-copy-id"
brew "supervisor"
brew "tmux"
brew "watch"

cask "atom"
cask "docker"
cask "google-chrome"
cask "iterm2"
cask "java" unless system "/usr/libexec/java_home --failfast"
cask "postgres"
cask "postico"
cask "resolume-arena"
cask "spectacle"
cask "sublime-text"
